### ISSUE TITLE
Accidental Overwriting certificates that are not from LetsEncrypt

### ISSUE THREAD

**Issue by fernviridian** [tozny/rancher-lets-encrypt#24]
Steps to reproduce:
1. Add cert from other Certificate Authority (Godaddy, Verisign)
2. Name cert in Rancher UI the same as domain used in Rancher-lets-encrypt (test.example.com)
3. Start Rancher-lets-encrypt service
4. RLE looks for certificate in Rancher API that matches hostname (test.example.com)
5. RLE finds cert, but it is not signed by LetsEncrypt CA, so it deletes the existing (test.example.com) certificate
6. RLE then provisions a Lets-encrypt certificate matching (test.example.com) and uploads it through the Rancher API.

Outcome: 
Old certificate from CA other than Lets-Encrypt is overwritten.

Desired:
Any certificate that is named the same as hostname, but not signed by either "Staging" or "Production" Lets-encrypt CA should be ignored.

**Comment by tvollstaedt** [comment]
Confirmed.
