### ISSUE TITLE
Certbot and dependencies versions

### ISSUE THREAD

**Issue by fboaventura** [tozny/rancher-lets-encrypt#37]
Need to upgrade versions for certbot and acme.

**Comment by galxy25** [comment]
@fboaventura to what versions? Any particular reason the upgrade is needed(e.g. security issues or desire to use this open source code with newer libraries)?

**Comment by fboaventura** [comment]
Hi @galxy25!

I usually open these issues to attach to a PR (#38), but here is the info:

| package | from  | to | reason |
-----------|-------|----|---------|
| requests | 2.21.0 | 2.22.0 | To use newer version |
| certbot | 0.32.0 | 0.40.1 | Compatibility reasons |
| acme | 0.32.0 | 0.40.1 | Compatibility reasons |

`certbot` and `acme` stopped working with version 0.32.0.

Cheers,
