### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by adi90x** [tozny/rancher-lets-encrypt#5]
Hello, 

Is it suppose to automatically create a new certificate when a new path is add in the load balancer ? 
(Almost the same way JrCs/docker-letsencrypt-nginx-proxy-companion do ? ) 
Or Am I wrong ? and domain must be add to environment variable in letsencrypt-nginx and restarted ? ) 

Regards,

**Comment by ericmann** [comment]
Yes, the domains must be specified in the environment.
