### ISSUE TITLE
NameError: global name 'HOST_CHECK_LOOP_TIME' is not defined

### ISSUE THREAD

**Issue by PhilipSchmid** [tozny/rancher-lets-encrypt#7]
Hi there,

When I try to start the Docker containers, I get the following error:
```bash
[root@srv rancher-lets-encrypt]# docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use the bundle feature of the Docker experimental build.

More info:
https://docs.docker.com/compose/bundles

Recreating rancherletsencrypt_rancher-lets-encrypt_1
Starting rancherletsencrypt_letsencrypt-nginx_1
Attaching to rancherletsencrypt_letsencrypt-nginx_1, rancherletsencrypt_rancher-lets-encrypt_1
rancher-lets-encrypt_1  | t find an Environment variable set.
rancher-lets-encrypt_1  | 'CATTLE_URL'
rancher-lets-encrypt_1  | Traceback (most recent call last):
rancher-lets-encrypt_1  |   File "/python/rancher.py", line 393, in <module>
rancher-lets-encrypt_1  |     service.check_hostnames_and_ports()
rancher-lets-encrypt_1  |   File "/python/rancher.py", line 362, in check_hostnames_and_ports
rancher-lets-encrypt_1  |     print "Sleeping during host lookups for {0} seconds".format(HOST_CHECK_LOOP_TIME)
rancher-lets-encrypt_1  | NameError: global name 'HOST_CHECK_LOOP_TIME' is not defined
```

My letsencrypt.env:
```
[root@srv rancher-lets-encrypt]# cat letsencrypt.env 
DOMAINS=srv.example.com
CERTBOT_WEBROOT=/var/www
CERTBOT_EMAIL=myself@example.com
RENEW_BEFORE_DAYS=14
LOOP_TIME=300
# Staging = True will get you a cert with the CA Fake, while Staging = False will use production Let's Encrypt to get the Let's Encrypt V3 CA.
STAGING=False
HOST_CHECK_PORT=80
HOST_CHECK_LOOP_TIME=10
```
As you can see, the HOST_CHECK_LOOP_TIME variable is set. Do you have any ideas why this error happens?

Thanks!

Ragards,
Philip

**Comment by ericmann** [comment]
The entire point of this project is to enable LE cert management with Rancher ... why are you using Docker Compose directly instead of letting Rancher manage things for you?

**Comment by PhilipSchmid** [comment]
Well this point is clear, but I tried to run it manually in order to check if runs before I try to add it to Rancher itself. 

Sorry for the question but what's the easiest way to add this service to my Rancher installation? Could you provide me a link to a manual page?

Thanks

Regards,
Philip

**Comment by PhilipSchmid** [comment]
Sorry my bad. It seems to work after importing the service over rancher CLI.

```
rancher up -d -s LetsEncrypt
```

**Comment by PhilipSchmid** [comment]
I also had to add 
```
ports:
    - 80:80/tcp
```
to the docker-compose.yml file so the nginx is reachable from the internet. Should this be like this?

**Comment by ericmann** [comment]
To make it accessible, yes. The idea is that Nginx (and the rest of your stack) would be behind a load balancer and wouldn't be public otherwise.

**Comment by fernviridian** [comment]
https://github.com/tozny/rancher-lets-encrypt/blob/master/traffic-manager/docker-compose.yml#L3 shows us using the Rancher load balancer to receive internet traffic on port 80. Then on https://github.com/tozny/rancher-lets-encrypt/blob/master/traffic-manager/docker-compose.yml#L9 shows us directing traffic from server:80/.well-known/acme-challenge/ directory to the lets-encrypt-nginx container for verification. The load balancer manages all open ports on the internet and serves as a reverse proxy to the correct container managed by Rancher.
